---
kind: pipeline
type: docker
name: build

steps:
  - name: build and push image
    image: quay.io/buildah/stable
    privileged: true
    network_mode: host
    environment:
      REGISTRY_HOST: "harbor.k8s.lan/k8s"
      CONTAINERFILE: "./deploy/container/Containerfile"
      STORAGE_DRIVER: "overlay"
      FORMAT: "oci"
      CONTEXT: "."
      TLSVERIFY: "false"
      USERNAME: "robot-drone-ci"
      PASSWORD:
        from_secret: harbor_registry_drone_password
    commands:
      - |
        echo "Build image..."
        buildah --storage-driver=$${STORAGE_DRIVER} bud --format=$${FORMAT} \
        --tls-verify=$${TLSVERIFY} --no-cache \
        -f $${CONTAINERFILE} \
        -t $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:latest \
        -t $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER} \
        --layers=true $${CONTEXT}
      - |
        echo "Push image with latest tag..."
        buildah push --creds=$${USERNAME}:$${PASSWORD} \
        --tls-verify=$${TLSVERIFY} \
        $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:latest \
        docker://$${REGISTRY_HOST}/$${DRONE_REPO_NAME}:latest
      - |
        echo "Push image with buildnumber tag..."
        buildah push --creds=$${USERNAME}:$${PASSWORD} \
        --tls-verify=$${TLSVERIFY} \
        --digestfile=/tmp/image-digest \
        $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER} \
        docker://$${REGISTRY_HOST}/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER}

---
kind: pipeline
type: docker
name: notify

depends_on:
  - build

trigger:
  status:
    - success
    - failure

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: cicd
      template: >
        {{#success build.status}}
          Build {{build.number}} of {{repo.name}} succeeded.
        {{else}}
          Build {{build.number}} of {{repo.name}} failed.
        {{/success}}

---
kind: secret
name: harbor_registry_drone_password
get:
  path: harbor-registry-drone-password
  name: harbor-robot-password

---
kind: secret
name: github_ssh_key
get:
  path: github-ssh-keys
  name: id_rsa

---
kind: secret
name: slack_webhook_url
get:
  path: slack-webhook-url
  name: url
